version: "3" # version of docker-compose we want to use

services:

  # ––––– Application –––––
  # ––––––––––––––––––––––
  client:
    container_name: client
    # build represents where to find docker file (i.e. /app folder)
    build: app
    env_file:
      - .env
    depends_on: 
      - api
    networks: 
      - nginx_client
  api:
    container_name: flask-api
    # build represents where to find docker file (i.e. /api folder)
    build: api
    restart: always
    # pass environment variables from docker environment
    env_file:
      - .env
    depends_on:
      - db
    networks: 
      - nginx_api
      - api_db
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    # Add persistence to postgres
    volumes:
      - my_database:/var/lib/postgresql/data
    env_file:
      - .env
    networks: 
      - api_db

# ––––– Monitoring –––––
# ––––––––––––––––––––––
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports: 
      - 9000:3000
    depends_on: 
      - prometheus
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks: 
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/roots:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

  # ––––– Nginx –––––
  # ––––––––––––––––––––––
  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/nginx-conf.conf:/etc/nginx/user_conf.d/default.conf:ro
    depends_on:
      - client
    networks: 
      - nginx_api
      - nginx_client
      - monitoring

volumes:
  my_database:
  nginx_secrets:

networks: 
  api_db:
  nginx_client:
  nginx_api:
  monitoring:

