version: "3" # version of docker-compose we want to use

services: 
  client:
    # build represents where to find docker file (i.e. /app foleder)
    build: app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on: 
      - api
  api:
    container_name: flask-api
    ports: 
      - 5000:5000
    # build represents where to find docker file (i.e. /api foleder)
    build: api
    restart: always
    # pass environment variables from docker environment
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: postgre-db
    image: postgres
    restart: always
    # Add persistence to postgres
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db:

  # nginx
  # nginx:
  #   container_name: nginx
  #   image: jonasal/nginx-certbot:latest
  #   restart: unless-stopped
  #   env_file:
  #     - ./nginx-certbot.env
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - nginx_secrets:/etc/letsencrypt
  #     - ./user_conf.d:/etc/nginx/user_conf.d
  #   depends_on:
  #     - web

  # cadvisor:
  #   container_name: cadvisor
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - /:/roots:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro

<<<<<<< HEAD
<<<<<<< HEAD
volumes:
  my_database:
#   nginx_secrets:
=======

>>>>>>> 570f7481be49953626b0fbe00f536afd64813b82

=======
>>>>>>> 505364ae1b8ec491e74f4f51e14f355e5d139288
# We are no longer exposing 5432  but flask is still able 
# to access the db since both images are in the same network
# Now web container depends on db, so the first db container
# is started onle when web container is started
# 