version: "3" # version of docker-compose we want to use

services: 
  client:
    # build represents where to find docker file (i.e. /app folder)
    container_name: client
    build: app
    volumes: 
      - ./app:/app
    env_file:
      - .env
    ports:
      - 80:3000
    depends_on: 
      - api

  api:
    container_name: flask-api
    volumes:
      - ./api:/api
    ports: 
      - 5000:5000
    # build represents where to find docker file (i.e. /api folder)
    build: api
    restart: always
    # pass environment variables from docker environment
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres
    restart: always
    # Add persistence to postgres
    volumes:
      - my_database:/var/lib/postgresql/data
    env_file:
      - .env

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/roots:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  my_database:


# We are no longer exposing 5432, but Flask is still able 
# to access the db since both images are on the same network.
# Now web container depends on db, so the first db container
# is started only when web container is started.