"""empty message

Revision ID: 040cd0a4b391
Revises: 123ff6fb2a5b
Create Date: 2021-08-05 18:45:03.962075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040cd0a4b391'
down_revision = '123ff6fb2a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_topic', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_topic')
    # ### end Alembic commands ###
