name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to AWS EC2 Instance"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key-2.pem
          chmod 600 ~/.ssh/deploy-key-2.pem
          cat >>~/.ssh/config <<END
          Host my-vm
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key-2.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Deploy site
        run: ssh my-vm 'cd ${{ secrets.PROJECT_DIR }} && git fetch && git reset --hard origin/master && docker-compose down && docker-compose up -d --build'

      - name: Check deploy status
        run: ssh my-vm 'cd ${{ secrets.PROJECT_DIR }} && docker-compose ps'

      - name: Check out Git repository
        uses: actions/checkout@v2

      # - name: Verify deployment
      #   Comment out when we add prod-test.sh
      #   run: sleep 5 && bash prod-test.sh

      - name: Discord success notification
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Deployment Successful! Check it out at {INSERT URL HERE}"

      - name: Discord failure notification
        if: ${{ failure() }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Deployment Failed."
